services:
#  api:
#    image: 'my-rds-app:0.0.1-SNAPSHOT'
#    depends_on:
#     - mysql
#    restart: always
#    environment:
#      - 'RDS_HOSTNAME=rds-mysql-db.cwqxnjcd57jp.us-east-1.rds.amazonaws.com'
#      - 'RDS_PORT=3306'
#      - 'RDS_DB_NAME=rds-mysql-db'
#      - 'RDS_USERNAME=admin'
#      - 'RDS_PASSWORD=CfJwJvf58B09a8K'
#      - 'SPRING_PROFILES_ACTIVE=docker'
#    ports:
#      - '8080:8080'
#    networks:
#      - springapimysql-net

  mysql:
    image: 'mysql:8.0.34'
    restart: always
    environment:
      - 'MYSQL_DATABASE=db'
      - 'MYSQL_PASSWORD=DRcogjV7y@rcvez@CS#yk2F2PR9eC4kUnAjkgBgD53H59!SUQ$'
      - 'MYSQL_ROOT_PASSWORD=DRcogjV7y@rcvez@CS#yk2F2PR9eC4kUnAjkgBgD53H59!SUQ$'
      - 'MYSQL_USER=vzahnitko'
    ports:
      - '3306:3306'
    networks:
      - springapimysql-net
    volumes:
      - db:/var/lib/mysql

networks:
  springapimysql-net:
volumes:
  db: