services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=db'
      - 'MYSQL_PASSWORD=DRcogjV7y@rcvez@CS#yk2F2PR9eC4kUnAjkgBgD53H59!SUQ$'
      - 'MYSQL_ROOT_PASSWORD=DRcogjV7y@rcvez@CS#yk2F2PR9eC4kUnAjkgBgD53H59!SUQ$'
      - 'MYSQL_USER=vzahnitko'
    ports:
      - '3306'
